name: Download CICMalAnal2017

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Ransomware APKs with wget
        run: |
          wget -c --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
          --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
          --header="Accept-Language: en-US,en;q=0.5" \
          --header="Connection: keep-alive" \
          http://cicresearch.ca/CICDataset/CICMalAnal2017/Dataset/APKs/Ransomware-APKs.zip
          echo "下载完成"
          ls -lh Ransomware-APKs.zip
          # 检查文件大小是否接近 100MB
          if [ $(stat -c%s Ransomware-APKs.zip) -lt 100000000 ]; then
            echo "文件大小小于 100MB，下载可能不完整。"
            exit 1
          fi
          # 检查文件类型是否为 ZIP
          if ! file Ransomware-APKs.zip | grep -q "Zip archive"; then
            echo "下载的文件不是 ZIP 格式，可能是错误页面。"
            exit 1
          fi

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          tag: cic-apks
          artifacts: "Ransomware-APKs.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
