name: Download CICMalAnal2017

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # For uploading to release

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Ransomware APKs
        run: |
          wget -c http://cicresearch.ca/CICDataset/CICMalAnal2017/Dataset/APKs/Ransomware-APKs.zip
          echo "Download completed"
          ls -lh Ransomware-APKs.zip  # Verify size

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          tag: cic-apks
          artifacts: "Ransomware-APKs.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
